#!/usr/bin/env node
/*
 * The per-row cutover report.
 *
 * docs/adr/0004 promises that every existing row keeps the status it displayed
 * on cutover day and that no page is de-indexed. This script proves it row by
 * row: it takes the two snapshots written by scripts/snapshot-states.mjs (one
 * before the state change, one after), joins them to the typed fields each row
 * carried, and writes docs/migrations/2026-08-cutover-states.md with one table
 * per page. Code games, daily-link games, cheat games and dataset pages are all
 * compared. A row whose displayed state moved in a direction the mapping does
 * not allow, a page or row present in only one snapshot, or a page that lost its
 * index entry is printed as a violation and the exit code is 1.
 *
 *   node scripts/cutover-report.mjs before.json after.json
 */

import { readFile, readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { derivedRowId } from '../src/lib/normalise.ts';

const root = path.resolve(fileURLToPath(new URL('..', import.meta.url)));
const [beforePath, afterPath] = process.argv.slice(2);
if (!beforePath || !afterPath) {
  console.error('usage: node scripts/cutover-report.mjs <before.json> <after.json>');
  process.exit(2);
}

const before = JSON.parse(await readFile(beforePath, 'utf8'));
const after = JSON.parse(await readFile(afterPath, 'utf8'));
const operations = JSON.parse(await readFile(path.join(root, 'src/content/operations.json'), 'utf8'));

/*
 * The old display vocabulary and the new one. The mapping is the only movement
 * the cutover allows: a row may relabel, never demote or promote.
 */
// The pre-cutover labels, named here only to print the "displayed before" column.
const OLD_LABELS = {
  verified: 'Verified active', reported: 'Source-reported', stale: 'Needs recheck', // retired-vocabulary: allow, historical column
  unverified: 'Unconfirmed', expired: 'Expired',
  active: 'Active', removed: 'Removed',
};
const NEW_LABELS = {
  verified: '★ Verified', active: 'Active · as published',
  listed: 'Listed · awaiting editor verification', expired: 'Expired',
};
const ALLOWED = {
  // operational entries
  verified: new Set(['verified']),
  reported: new Set(['listed']),
  stale: new Set(['listed']),
  unverified: new Set(['listed']),
  expired: new Set(['expired']),
  // dataset rows
  active: new Set(['active']),
  removed: new Set(['expired']),
};

const violations = [];
const lines = [];
const push = (...items) => lines.push(...items);

const summary = { operational: {}, datasets: {}, index: { before: [], after: [] } };
const tally = (bucket, state) => { bucket[state] = (bucket[state] ?? 0) + 1; };

/*
 * Set equality both ways. A snapshot that lost a section, or a page or row that
 * exists on one side only, would otherwise read as "nothing moved"; a missing id
 * on either side is a violation.
 */
const requireSameIds = (label, beforeIds, afterIds) => {
  for (const id of beforeIds) if (!afterIds.has(id)) violations.push(`${label} ${id} missing from the after snapshot`);
  for (const id of afterIds) if (!beforeIds.has(id)) violations.push(`${label} ${id} missing from the before snapshot`);
};

const totalsOf = (snapshot) => {
  const games = snapshot.games ?? [];
  const cheatGames = snapshot.cheatGames ?? [];
  const datasets = snapshot.datasets ?? [];
  return {
    games: games.length,
    cheatGames: cheatGames.length,
    entries: [...games, ...cheatGames].reduce((total, game) => total + game.entries.length, 0),
    pages: datasets.length,
    rows: datasets.reduce((total, page) => total + page.rows.length, 0),
  };
};
const totals = { before: totalsOf(before), after: totalsOf(after) };

push('# Cutover states, row by row', '',
  `Before snapshot taken ${before.takenAt}; after snapshot taken ${after.takenAt}. Generated by \`scripts/cutover-report.mjs\`; do not edit by hand.`, '',
  'Each row shows what it carried in the data, what it displayed before the cutover, and what it displays after. The only movement allowed is a relabel along the mapping in docs/adr/0004: Verified active → ★ Verified; Source-reported, Needs recheck and Unconfirmed → Listed · awaiting editor verification; Active → Active · as published; Expired and Removed → Expired. Anything else is a violation and is listed at the end.', ''); // retired-vocabulary: allow, historical mapping

/* ---------------------------------------------------------------- operational */

const eventsFor = (entryType, entryId) => operations.verificationEvents
  .filter((event) => event.entryType === entryType && event.entryId === entryId)
  .sort((left, right) => Date.parse(right.checkedAt) - Date.parse(left.checkedAt));

/*
 * One comparison for every game list the index gate reads: code and daily-link
 * games in `games`, cheat games in `cheatGames`. Each is joined on slug, its
 * index flag compared, and every entry joined on id to its newest event.
 */
const compareGames = ({ kind, beforeGames, afterGames, entryTypeOf, defaultSurface, indexName }) => {
  const laterBySlug = new Map(afterGames.map((game) => [game.slug, game]));
  requireSameIds(kind, new Set(beforeGames.map((game) => game.slug)), new Set(afterGames.map((game) => game.slug)));
  for (const game of beforeGames) {
    const later = laterBySlug.get(game.slug);
    if (!later) continue;
    if (game.indexable) summary.index.before.push(indexName(game.slug));
    if (later.indexable) summary.index.after.push(indexName(game.slug));
    if (game.indexable && !later.indexable) violations.push(`${kind} ${game.slug} was indexable and is not`);
    requireSameIds(`${kind} ${game.slug} entry`, new Set(game.entries.map((item) => item.id)), new Set(later.entries.map((item) => item.id)));
    if (!game.entries.length) continue;

    push(`### ${game.slug} (${game.surface ?? defaultSurface}, ${game.publicationState}; indexable ${game.indexable} → ${later.indexable})`, '',
      '| id | newest event | displayed before | displayed after |', '|---|---|---|---|');
    const laterEntries = new Map(later.entries.map((item) => [item.id, item.state]));
    for (const entry of game.entries) {
      const afterState = laterEntries.get(entry.id);
      const event = eventsFor(entryTypeOf(game), entry.id)[0];
      const typed = event ? `${event.result} · ${event.method} · ${event.checkedAt}` : 'none';
      tally(summary.operational, `${entry.state}→${afterState ?? '(missing)'}`);
      // A missing id is already a violation from requireSameIds; only a present row is checked against the mapping.
      if (afterState !== undefined && !ALLOWED[entry.state]?.has(afterState)) violations.push(`${game.slug} ${entry.id}: ${entry.state} → ${afterState}`);
      push(`| ${entry.id} | ${typed} | ${OLD_LABELS[entry.state] ?? entry.state} | ${afterState === undefined ? '(missing)' : NEW_LABELS[afterState] ?? afterState} |`);
    }
    push('');
  }
};

push('## Operational entries', '');
compareGames({
  kind: 'game',
  beforeGames: before.games ?? [],
  afterGames: after.games ?? [],
  entryTypeOf: (game) => (game.surface === 'daily' ? 'dailyLink' : 'code'),
  defaultSurface: 'codes',
  indexName: (slug) => slug,
});

push('## Cheat pages', '');
compareGames({
  kind: 'cheat game',
  beforeGames: before.cheatGames ?? [],
  afterGames: after.cheatGames ?? [],
  entryTypeOf: () => 'cheat',
  defaultSurface: 'cheats',
  indexName: (slug) => `cheats/${slug}`,
});

/* ---------------------------------------------------------------- datasets */

/*
 * The typed fields of every row in a data file, keyed on the id the row carries
 * in the snapshots. The id is derived exactly as normalise does (the file's own
 * slug, the row's table or the first table, the row name), so the join holds
 * however the rows are ordered and a printed typed column can never describe a
 * neighbouring row.
 */
const readTypedRows = async (page) => {
  const [section, slug] = page.split('/');
  const raw = JSON.parse(await readFile(path.join(root, 'src/data', section, `${slug}.json`), 'utf8'));
  const pageSlug = raw.slug ?? slug;
  const firstTableId = Object.keys(raw.tables ?? {})[0] ?? '';
  return new Map((raw.rows ?? []).map((row) => [
    row.id ?? derivedRowId(pageSlug, row.table ?? firstTableId, row.name ?? ''),
    row,
  ]));
};

push('## Dataset rows', '');
const beforePages = before.datasets ?? [];
const afterPagesList = after.datasets ?? [];
const afterPages = new Map(afterPagesList.map((page) => [page.page, page]));
requireSameIds('dataset page', new Set(beforePages.map((page) => page.page)), new Set(afterPagesList.map((page) => page.page)));
for (const page of beforePages) {
  const later = afterPages.get(page.page);
  if (!later) continue;
  const typedById = await readTypedRows(page.page);
  requireSameIds(`${page.page} row`, new Set(page.rows.map((row) => row.id)), new Set(later.rows.map((row) => row.id)));

  push(`### ${page.page}`, '', '| id | typed status · confidence · last_verified_at | displayed before | displayed after |', '|---|---|---|---|');
  const laterRows = new Map(later.rows.map((row) => [row.id, row.state]));
  for (const row of page.rows) {
    const afterState = laterRows.get(row.id);
    const typed = typedById.get(row.id) ?? {};
    const typedText = `${typed.status ?? '(none)'} · ${typed.confidence ?? '(none)'} · ${typed.last_verified_at ?? '(none)'}`;
    tally(summary.datasets, `${row.state}→${afterState ?? '(missing)'}`);
    if (afterState !== undefined && !ALLOWED[row.state]?.has(afterState)) violations.push(`${page.page} ${row.id}: ${row.state} → ${afterState}`);
    push(`| ${row.id} | ${typedText} | ${OLD_LABELS[row.state] ?? row.state} | ${afterState === undefined ? '(missing)' : NEW_LABELS[afterState] ?? afterState} |`);
  }
  push('');
}

/* ---------------------------------------------------------------- summary */

const summaryLines = ['## Summary', '',
  '| Surface | Movement | Rows |', '|---|---|---|'];
for (const [movement, count] of Object.entries(summary.operational)) summaryLines.push(`| operational | ${movement} | ${count} |`);
for (const [movement, count] of Object.entries(summary.datasets)) summaryLines.push(`| dataset | ${movement} | ${count} |`);
const totalsLine = (label, count) =>
  `${label} snapshot: ${count.games} games, ${count.cheatGames} cheat games, ${count.entries} operational entries, ${count.pages} dataset pages, ${count.rows} dataset rows.`;
summaryLines.push('',
  totalsLine('Before', totals.before),
  totalsLine('After', totals.after),
  `Indexable operational pages before (code, daily-link and cheat pages): ${summary.index.before.length} (${summary.index.before.join(', ')}).`,
  `Indexable operational pages after: ${summary.index.after.length} (${summary.index.after.join(', ')}).`,
  `Pages de-indexed: ${summary.index.before.filter((slug) => !summary.index.after.includes(slug)).length}.`, '');

const violationLines = violations.length
  ? ['## Violations', '', ...violations.map((item) => `- ${item}`), '']
  : ['## Violations', '', 'None. Both snapshots hold the same games, cheat games, entries, dataset pages and rows; every row moved only along the allowed mapping and no page lost its index entry.', ''];

const document = [...lines.slice(0, 5), ...summaryLines, ...violationLines, ...lines.slice(5)].join('\n');
const out = path.join(root, 'docs/migrations/2026-08-cutover-states.md');
await writeFile(out, document);

console.log(summaryLines.join('\n'));
console.log(violations.length ? `\n${violations.length} violation(s):\n${violations.map((item) => `  ${item}`).join('\n')}` : '\nNo violations.');
console.log(`\nWritten ${path.relative(root, out)}`);
process.exit(violations.length ? 1 : 0);
